<?php

declare(strict_types=1);

namespace NksHub\NetteSso\OAuth2;

use League\OAuth2\Client\Provider\GenericProvider;
use League\OAuth2\Client\Provider\Exception\IdentityProviderException;
use League\OAuth2\Client\Token\AccessToken;
use Nette\Http\Session;
use Nette\Http\SessionSection;
use Nette\Security\SimpleIdentity;
use NksHub\NetteSso\Exceptions\AuthenticationFailedException;

/**
 * OAuth2/OpenID Connect Provider for SSO authentication
 *
 * Provides secure OAuth2 authentication flow with CSRF protection,
 * role mapping, and Nette Identity creation.
 */
class SsoProvider
{
	private GenericProvider $provider;
	private SessionSection $session;

	/**
	 * @param string[] $adminGroups List of groups that grant admin access
	 */
	public function __construct(
		private readonly string $clientId,
		private readonly string $clientSecret,
		private readonly string $redirectUri,
		private readonly string $authorizeUrl,
		private readonly string $tokenUrl,
		private readonly string $userinfoUrl,
		private readonly array $adminGroups,
		Session $sessionManager,
	) {
		$this->initializeProvider();
		$this->session = $sessionManager->getSection('sso');
	}

	private function initializeProvider(): void
	{
		$this->provider = new GenericProvider([
			'clientId' => $this->clientId,
			'clientSecret' => $this->clientSecret,
			'redirectUri' => $this->redirectUri,
			'urlAuthorize' => $this->authorizeUrl,
			'urlAccessToken' => $this->tokenUrl,
			'urlResourceOwnerDetails' => $this->userinfoUrl,
			'scopes' => 'openid email profile groups',
			'scopeSeparator' => ' ',
			'pkceMethod' => GenericProvider::PKCE_METHOD_S256,
		]);
	}

	/**
	 * Get authorization URL for redirect to SSO login
	 *
	 * Generates authorization URL and stores state token in session for CSRF protection.
	 * Also generates and stores a nonce for ID token replay protection.
	 *
	 * @param array<string, mixed> $options Additional OAuth2 options
	 */
	public function getAuthorizationUrl(array $options = []): string
	{
		$nonce = bin2hex(random_bytes(16));
		$this->session->nonce = $nonce;

		$url = $this->provider->getAuthorizationUrl(array_merge([
			'scope' => ['openid', 'email', 'profile', 'groups'],
			'nonce' => $nonce,
		], $options));

		// Store state token in session for CSRF validation
		$this->session->state = $this->provider->getState();

		// Persist PKCE code verifier generated by the provider
		$this->session->pkceCode = $this->provider->getPkceCode();

		return $url;
	}

	/**
	 * Get state token for CSRF protection
	 *
	 * Returns the state token stored in session after getAuthorizationUrl() call.
	 */
	public function getState(): string
	{
		return $this->session->state ?? '';
	}

	/**
	 * Get PKCE code verifier stored in session
	 */
	public function getPkceCode(): ?string
	{
		return $this->session->pkceCode ?? null;
	}

	/**
	 * Restore PKCE code verifier into the provider (must be called before getAccessToken)
	 */
	public function setPkceCode(?string $pkceCode): void
	{
		$this->provider->setPkceCode($pkceCode);
	}

	/**
	 * Validate state token from OAuth2 callback
	 *
	 * @throws AuthenticationFailedException When state validation fails
	 */
	public function validateState(string $state): void
	{
		$sessionState = $this->session->state ?? null;

		if (!$sessionState || !hash_equals($sessionState, $state)) {
			throw new AuthenticationFailedException('Invalid state token (CSRF protection failed)');
		}

		// Clear state after validation
		unset($this->session->state);

		// Restore PKCE code verifier so the token exchange can include the code_verifier
		$this->setPkceCode($this->session->pkceCode ?? null);
		unset($this->session->pkceCode);
	}

	/**
	 * Exchange authorization code for access token
	 *
	 * @throws AuthenticationFailedException
	 */
	public function getAccessToken(string $code): AccessToken
	{
		try {
			return $this->provider->getAccessToken('authorization_code', [
				'code' => $code
			]);
		} catch (IdentityProviderException $e) {
			throw new AuthenticationFailedException(
				'Failed to exchange authorization code for access token: ' . $e->getMessage(),
				$e->getCode(),
				$e
			);
		}
	}

	/**
	 * Get user info from access token
	 *
	 * @return array{
	 *   sub: string,
	 *   email: string,
	 *   name: string,
	 *   preferred_username?: string,
	 *   groups?: string[],
	 *   picture?: string
	 * }
	 * @throws AuthenticationFailedException
	 */
	public function getUserInfo(AccessToken $token): array
	{
		try {
			$user = $this->provider->getResourceOwner($token);
			return $user->toArray();
		} catch (IdentityProviderException $e) {
			throw new AuthenticationFailedException(
				'Failed to retrieve user info: ' . $e->getMessage(),
				$e->getCode(),
				$e
			);
		}
	}

	/**
	 * Complete OAuth2 authentication flow
	 *
	 * Validates state token, exchanges code for token, and retrieves user data.
	 *
	 * @return array{
	 *   user: array,
	 *   token: AccessToken
	 * }
	 * @throws AuthenticationFailedException
	 */
	public function authenticate(string $code, string $state): array
	{
		// Validate CSRF token (also restores + clears PKCE verifier from session)
		$this->validateState($state);

		// Retrieve and clear nonce before token exchange
		$expectedNonce = $this->session->nonce ?? null;
		unset($this->session->nonce);

		// Exchange code for token (PKCE code_verifier is included automatically)
		$token = $this->getAccessToken($code);

		// Get user info
		$user = $this->getUserInfo($token);

		// Validate nonce from ID token to prevent replay attacks
		if ($expectedNonce !== null) {
			$this->validateNonce($user, $expectedNonce);
		}

		return [
			'user' => $user,
			'token' => $token
		];
	}

	/**
	 * Validate nonce claim in ID token / userinfo response
	 *
	 * @param array<string, mixed> $userData
	 * @throws AuthenticationFailedException When nonce is missing or does not match
	 */
	private function validateNonce(array $userData, string $expectedNonce): void
	{
		$receivedNonce = $userData['nonce'] ?? null;

		if ($receivedNonce === null || !hash_equals($expectedNonce, (string) $receivedNonce)) {
			throw new AuthenticationFailedException('Invalid nonce (ID token replay attack detected)');
		}
	}

	/**
	 * Check if user has admin access based on groups
	 *
	 * @param array<string, mixed> $userData User data from OAuth2 provider
	 */
	public function hasAdminAccess(array $userData): bool
	{
		$groups = $userData['groups'] ?? [];

		foreach ($groups as $group) {
			if (in_array(strtolower($group), array_map('strtolower', $this->adminGroups), true)) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Create Nette Identity from OAuth2 user data
	 *
	 * Maps OAuth2 user data and groups to Nette Identity with role.
	 *
	 * @param array<string, mixed> $userData User data from OAuth2 provider
	 * @param string|null $roleOverride Override role detection (e.g., from database)
	 */
	public function createIdentity(array $userData, ?string $roleOverride = null): SimpleIdentity
	{
		$groups = $userData['groups'] ?? [];
		$role = $roleOverride ?? 'viewer';

		// Auto-detect role from groups if not overridden
		if (!$roleOverride) {
			$role = $this->detectRoleFromGroups($groups);
		}

		return new SimpleIdentity(
			$userData['sub'], // OAuth2 subject (unique ID)
			$role,
			[
				'email' => $userData['email'] ?? null,
				'name' => $userData['name'] ?? $userData['preferred_username'] ?? 'Unknown',
				'username' => $userData['preferred_username'] ?? null,
				'picture' => $userData['picture'] ?? null,
				'groups' => $groups,
				'sso_provider' => 'authentik'
			]
		);
	}

	/**
	 * Detect user role from OAuth2 groups
	 *
	 * @param string[] $groups
	 */
	private function detectRoleFromGroups(array $groups): string
	{
		$groupsLower = array_map('strtolower', $groups);

		// Priority: superadmin > admin > moderator > viewer
		if (in_array('superadmin', $groupsLower, true) || in_array('superadmin-webs', $groupsLower, true)) {
			return 'superadmin';
		}

		if (in_array('admin', $groupsLower, true) || in_array('administrators', $groupsLower, true) || in_array('authentik admins', $groupsLower, true)) {
			return 'admin';
		}

		if (in_array('moderator', $groupsLower, true)) {
			return 'moderator';
		}

		return 'viewer';
	}

	/**
	 * Get configured admin groups
	 *
	 * @return string[]
	 */
	public function getAdminGroups(): array
	{
		return $this->adminGroups;
	}
}
